### ISSUE TITLE
Update year of your graduation

### ISSUE THREAD

**Issue by AnikethDeb2004** [kunalkeshan/kunalkeshan.dev#140]
![Screenshot (19)](https://github.com/kunalkeshan/kunalkeshan.dev/assets/137791848/974fa017-4f0e-4ffd-8b47-5f3aa2b22350)

**Comment by kunalkeshan** [comment]
Yooo, missed this. Thanks for updating @AnikethDeb2004.
If you're interested in fixing this, feel free to fork and update it to - **"presently in my final year"**

**Comment by AnikethDeb2004** [comment]
Yeah will work upon it.
